// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

const (
	AreaScopeOfQMCPresentNothing int = iota /* No components present */
	AreaScopeOfQMCPresentCellBased
	AreaScopeOfQMCPresentTABased
	AreaScopeOfQMCPresentTAIBased
	AreaScopeOfQMCPresentPLMNAreaBased
	AreaScopeOfQMCPresentChoiceExtensions
)

type AreaScopeOfQMC struct {
	Present          int
	CellBased        *CellBasedQMC     `aper:"valueExt"`
	TABased          *TABasedQMC       `aper:"valueExt"`
	TAIBased         *TAIBasedQMC      `aper:"valueExt"`
	PLMNAreaBased    *PLMNAreaBasedQMC `aper:"valueExt"`
	ChoiceExtensions *AreaScopeOfQMCExtIEs
}
