// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

const (
	AreaScopeOfMDTNRPresentNothing int = iota /* No components present */
	AreaScopeOfMDTNRPresentCellBased
	AreaScopeOfMDTNRPresentTABased
	AreaScopeOfMDTNRPresentPLMNWide
	AreaScopeOfMDTNRPresentTAIBased
	AreaScopeOfMDTNRPresentChoiceExtensions
)

type AreaScopeOfMDTNR struct {
	Present          int
	CellBased        *CellBasedMDTNR `aper:"valueExt"`
	TABased          *TABasedMDT     `aper:"valueExt"`
	PLMNWide         *struct{}
	TAIBased         *TAIBasedMDT `aper:"valueExt"`
	ChoiceExtensions *AreaScopeOfMDTNRExtIEs
}
