// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	CauseRadioNetworkPresentUnspecified                                              aper.Enumerated = 0
	CauseRadioNetworkPresentTxnrelocoverallExpiry                                    aper.Enumerated = 1
	CauseRadioNetworkPresentSuccessfulHandover                                       aper.Enumerated = 2
	CauseRadioNetworkPresentReleaseDueToNgranGeneratedReason                         aper.Enumerated = 3
	CauseRadioNetworkPresentReleaseDueTo5gcGeneratedReason                           aper.Enumerated = 4
	CauseRadioNetworkPresentHandoverCancelled                                        aper.Enumerated = 5
	CauseRadioNetworkPresentPartialHandover                                          aper.Enumerated = 6
	CauseRadioNetworkPresentHoFailureInTarget5GCNgranNodeOrTargetSystem              aper.Enumerated = 7
	CauseRadioNetworkPresentHoTargetNotAllowed                                       aper.Enumerated = 8
	CauseRadioNetworkPresentTngrelocoverallExpiry                                    aper.Enumerated = 9
	CauseRadioNetworkPresentTngrelocprepExpiry                                       aper.Enumerated = 10
	CauseRadioNetworkPresentCellNotAvailable                                         aper.Enumerated = 11
	CauseRadioNetworkPresentUnknownTargetID                                          aper.Enumerated = 12
	CauseRadioNetworkPresentNoRadioResourcesAvailableInTargetCell                    aper.Enumerated = 13
	CauseRadioNetworkPresentUnknownLocalUENGAPID                                     aper.Enumerated = 14
	CauseRadioNetworkPresentInconsistentRemoteUENGAPID                               aper.Enumerated = 15
	CauseRadioNetworkPresentHandoverDesirableForRadioReason                          aper.Enumerated = 16
	CauseRadioNetworkPresentTimeCriticalHandover                                     aper.Enumerated = 17
	CauseRadioNetworkPresentResourceOptimisationHandover                             aper.Enumerated = 18
	CauseRadioNetworkPresentReduceLoadInServingCell                                  aper.Enumerated = 19
	CauseRadioNetworkPresentUserInactivity                                           aper.Enumerated = 20
	CauseRadioNetworkPresentRadioConnectionWithUeLost                                aper.Enumerated = 21
	CauseRadioNetworkPresentRadioResourcesNotAvailable                               aper.Enumerated = 22
	CauseRadioNetworkPresentInvalidQosCombination                                    aper.Enumerated = 23
	CauseRadioNetworkPresentFailureInRadioInterfaceProcedure                         aper.Enumerated = 24
	CauseRadioNetworkPresentInteractionWithOtherProcedure                            aper.Enumerated = 25
	CauseRadioNetworkPresentUnknownPDUSessionID                                      aper.Enumerated = 26
	CauseRadioNetworkPresentUnkownQosFlowID                                          aper.Enumerated = 27
	CauseRadioNetworkPresentMultiplePDUSessionIDInstances                            aper.Enumerated = 28
	CauseRadioNetworkPresentMultipleQosFlowIDInstances                               aper.Enumerated = 29
	CauseRadioNetworkPresentEncryptionAndOrIntegrityProtectionAlgorithmsNotSupported aper.Enumerated = 30
	CauseRadioNetworkPresentNgIntraSystemHandoverTriggered                           aper.Enumerated = 31
	CauseRadioNetworkPresentNgInterSystemHandoverTriggered                           aper.Enumerated = 32
	CauseRadioNetworkPresentXnHandoverTriggered                                      aper.Enumerated = 33
	CauseRadioNetworkPresentNotSupported5QIValue                                     aper.Enumerated = 34
	CauseRadioNetworkPresentUeContextTransfer                                        aper.Enumerated = 35
	CauseRadioNetworkPresentImsVoiceEpsFallbackOrRatFallbackTriggered                aper.Enumerated = 36
	CauseRadioNetworkPresentUpIntegrityProtectionNotPossible                         aper.Enumerated = 37
	CauseRadioNetworkPresentUpConfidentialityProtectionNotPossible                   aper.Enumerated = 38
	CauseRadioNetworkPresentSliceNotSupported                                        aper.Enumerated = 39
	CauseRadioNetworkPresentUeInRrcInactiveStateNotReachable                         aper.Enumerated = 40
	CauseRadioNetworkPresentRedirection                                              aper.Enumerated = 41
	CauseRadioNetworkPresentResourcesNotAvailableForTheSlice                         aper.Enumerated = 42
	CauseRadioNetworkPresentUeMaxIntegrityProtectedDataRateReason                    aper.Enumerated = 43
	CauseRadioNetworkPresentReleaseDueToCnDetectedMobility                           aper.Enumerated = 44
	CauseRadioNetworkPresentN26InterfaceNotAvailable                                 aper.Enumerated = 45
	CauseRadioNetworkPresentReleaseDueToPreEmption                                   aper.Enumerated = 46
	CauseRadioNetworkPresentMultipleLocationReportingReferenceIDInstances            aper.Enumerated = 47
	CauseRadioNetworkPresentRsnNotAvailableForTheUp                                  aper.Enumerated = 48
	CauseRadioNetworkPresentNpnAccessDenied                                          aper.Enumerated = 49
	CauseRadioNetworkPresentCagOnlyAccessDenied                                      aper.Enumerated = 50
	CauseRadioNetworkPresentInsufficientUeCapabilities                               aper.Enumerated = 51
	CauseRadioNetworkPresentRedcapUeNotSupported                                     aper.Enumerated = 52
	CauseRadioNetworkPresentUnknownMBSSessionID                                      aper.Enumerated = 53
	CauseRadioNetworkPresentIndicatedMBSSessionAreaInformationNotServedByTheGNB      aper.Enumerated = 54
	CauseRadioNetworkPresentInconsistentSliceInfoForTheSession                       aper.Enumerated = 55
	CauseRadioNetworkPresentMisalignedAssociationForMulticastUnicast                 aper.Enumerated = 56
	CauseRadioNetworkPresentEredcapUeNotSupported                                    aper.Enumerated = 57
)

type CauseRadioNetwork struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:44"`
}
