// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

type ClockQualityAcceptanceCriteria struct {
	SynchronisationState    *aper.BitString                                                 `aper:"optional,sizeExt,sizeLB:8,sizeUB:8"`
	TraceabletoUTC          *aper.Enumerated                                                `aper:"optional,valueExt,valueLB:0,valueUB:0"`
	TraceabletoGNSS         *aper.Enumerated                                                `aper:"optional,valueExt,valueLB:0,valueUB:0"`
	ClockFrequencyStability *aper.BitString                                                 `aper:"optional,sizeLB:16,sizeUB:16"`
	ClockAccuracy           *int64                                                          `aper:"optional,valueExt,valueLB:1,valueUB:40000000"`
	ParentTImeSource        *aper.BitString                                                 `aper:"optional,sizeExt,sizeLB:16,sizeUB:16"`
	IEExtensions            *ProtocolExtensionContainerClockQualityAcceptanceCriteriaExtIEs `aper:"optional"`
}
