// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

type CompositeAvailableCapacity struct {
	CellCapacityClassValue *int64                                                      `aper:"optional,valueExt,valueLB:1,valueUB:100"`
	CapacityValue          int64                                                       `aper:"valueLB:0,valueUB:100"`
	IEExtensions           *ProtocolExtensionContainerCompositeAvailableCapacityExtIEs `aper:"optional"`
}
