// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

const (
	ECNMarkingorCongestionInformationReportingRequestPresentNothing int = iota /* No components present */
	ECNMarkingorCongestionInformationReportingRequestPresentECNMarkingAtRANRequest
	ECNMarkingorCongestionInformationReportingRequestPresentECNMarkingAtUPFRequest
	ECNMarkingorCongestionInformationReportingRequestPresentCongestionInformationRequest
	ECNMarkingorCongestionInformationReportingRequestPresentChoiceExtensions
)

type ECNMarkingorCongestionInformationReportingRequest struct {
	Present                      int
	ECNMarkingAtRANRequest       *ECNMarkingAtRANRequest
	ECNMarkingAtUPFRequest       *ECNMarkingAtUPFRequest
	CongestionInformationRequest *CongestionInformationRequest
	ChoiceExtensions             *ECNMarkingorCongestionInformationReportingRequestExtIEs
}
