// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	EUTRAPagingTimeWindowPresentS1  aper.Enumerated = 0
	EUTRAPagingTimeWindowPresentS2  aper.Enumerated = 1
	EUTRAPagingTimeWindowPresentS3  aper.Enumerated = 2
	EUTRAPagingTimeWindowPresentS4  aper.Enumerated = 3
	EUTRAPagingTimeWindowPresentS5  aper.Enumerated = 4
	EUTRAPagingTimeWindowPresentS6  aper.Enumerated = 5
	EUTRAPagingTimeWindowPresentS7  aper.Enumerated = 6
	EUTRAPagingTimeWindowPresentS8  aper.Enumerated = 7
	EUTRAPagingTimeWindowPresentS9  aper.Enumerated = 8
	EUTRAPagingTimeWindowPresentS10 aper.Enumerated = 9
	EUTRAPagingTimeWindowPresentS11 aper.Enumerated = 10
	EUTRAPagingTimeWindowPresentS12 aper.Enumerated = 11
	EUTRAPagingTimeWindowPresentS13 aper.Enumerated = 12
	EUTRAPagingTimeWindowPresentS14 aper.Enumerated = 13
	EUTRAPagingTimeWindowPresentS15 aper.Enumerated = 14
	EUTRAPagingTimeWindowPresentS16 aper.Enumerated = 15
)

type EUTRAPagingTimeWindow struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:15"`
}
