// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

type EUTRANCellReportItem struct {
	ECGI                                  EUTRACGI                                              `aper:"valueExt"`
	EUTRANCompositeAvailableCapacityGroup EUTRANCompositeAvailableCapacityGroup                 `aper:"valueExt"`
	EUTRANNumberOfActiveUEs               *EUTRANNumberOfActiveUEs                              `aper:"optional"`
	EUTRANNoofRRCConnections              *NGRANNoofRRCConnections                              `aper:"optional"`
	EUTRANRadioResourceStatus             *EUTRANRadioResourceStatus                            `aper:"valueExt,optional"`
	IEExtensions                          *ProtocolExtensionContainerEUTRANCellReportItemExtIEs `aper:"optional"`
}
