// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	EUTRAPagingEDRXCyclePresentHfhalf aper.Enumerated = 0
	EUTRAPagingEDRXCyclePresentHf1    aper.Enumerated = 1
	EUTRAPagingEDRXCyclePresentHf2    aper.Enumerated = 2
	EUTRAPagingEDRXCyclePresentHf4    aper.Enumerated = 3
	EUTRAPagingEDRXCyclePresentHf6    aper.Enumerated = 4
	EUTRAPagingEDRXCyclePresentHf8    aper.Enumerated = 5
	EUTRAPagingEDRXCyclePresentHf10   aper.Enumerated = 6
	EUTRAPagingEDRXCyclePresentHf12   aper.Enumerated = 7
	EUTRAPagingEDRXCyclePresentHf14   aper.Enumerated = 8
	EUTRAPagingEDRXCyclePresentHf16   aper.Enumerated = 9
	EUTRAPagingEDRXCyclePresentHf32   aper.Enumerated = 10
	EUTRAPagingEDRXCyclePresentHf64   aper.Enumerated = 11
	EUTRAPagingEDRXCyclePresentHf128  aper.Enumerated = 12
	EUTRAPagingEDRXCyclePresentHf256  aper.Enumerated = 13
)

type EUTRAPagingEDRXCycle struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:13"`
}
