// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

type EUTRANRadioResourceStatus struct {
	DLGBRPRBUsage             int64                                                      `aper:"valueLB:0,valueUB:100"`
	ULGBRPRBUsage             int64                                                      `aper:"valueLB:0,valueUB:100"`
	DLNonGBRPRBUsage          int64                                                      `aper:"valueLB:0,valueUB:100"`
	ULNonGBRPRBUsage          int64                                                      `aper:"valueLB:0,valueUB:100"`
	DLTotalPRBUsage           int64                                                      `aper:"valueLB:0,valueUB:100"`
	ULTotalPRBUsage           int64                                                      `aper:"valueLB:0,valueUB:100"`
	DLSchedulingPDCCHCCEUsage *int64                                                     `aper:"optional,valueLB:0,valueUB:100"`
	ULSchedulingPDCCHCCEUsage *int64                                                     `aper:"optional,valueLB:0,valueUB:100"`
	IEExtensions              *ProtocolExtensionContainerEUTRANRadioResourceStatusExtIEs `aper:"optional"`
}
