// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	EventTypePresentDirect                                              aper.Enumerated = 0
	EventTypePresentChangeOfServeCell                                   aper.Enumerated = 1
	EventTypePresentUePresenceInAreaOfInterest                          aper.Enumerated = 2
	EventTypePresentStopChangeOfServeCell                               aper.Enumerated = 3
	EventTypePresentStopUePresenceInAreaOfInterest                      aper.Enumerated = 4
	EventTypePresentCancelLocationReportingForTheUe                     aper.Enumerated = 5
	EventTypePresentChangeOfServingCellAndUEPresenceInTheAreaOfInterest aper.Enumerated = 6
)

type EventType struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:5"`
}
