// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

type FiveGProSeAuthorized struct {
	FiveGProSeDirectDiscovery        *FiveGProSeDirectDiscovery                            `aper:"optional"`
	FiveGProSeDirectCommunication    *FiveGProSeDirectCommunication                        `aper:"optional"`
	FiveGProSeLayer2UEtoNetworkRelay *FiveGProSeLayer2UEtoNetworkRelay                     `aper:"optional"`
	FiveGProSeLayer3UEtoNetworkRelay *FiveGProSeLayer3UEtoNetworkRelay                     `aper:"optional"`
	FiveGProSeLayer2RemoteUE         *FiveGProSeLayer2RemoteUE                             `aper:"optional"`
	IEExtensions                     *ProtocolExtensionContainerFiveGProSeAuthorizedExtIEs `aper:"optional"`
}
