// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

type HOReport struct {
	HandoverReportType     aper.Enumerated                           `aper:"valueExt,valueLB:0,valueUB:2"`
	HandoverCause          Cause                                     `aper:"valueLB:0,valueUB:5"`
	SourcecellCGI          NGRANCGI                                  `aper:"valueLB:0,valueUB:2"`
	TargetcellCGI          NGRANCGI                                  `aper:"valueLB:0,valueUB:2"`
	ReestablishmentcellCGI *NGRANCGI                                 `aper:"valueLB:0,valueUB:2"`
	SourcecellCRNTI        *aper.BitString                           `aper:"optional,sizeLB:16,sizeUB:16"`
	TargetcellinEUTRAN     *EUTRACGI                                 `aper:"valueExt,optional"`
	MobilityInformation    *MobilityInformation                      `aper:"optional"`
	UERLFReportContainer   *UERLFReportContainer                     `aper:"valueLB:0,valueUB:2"`
	IEExtensions           *ProtocolExtensionContainerHOReportExtIEs `aper:"optional"`
}
