// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

type ImmediateMDTNr struct {
	MeasurementsToActivate            MeasurementsToActivate
	M1Configuration                   *M1Configuration                                `aper:"valueExt,optional"`
	M4Configuration                   *M4Configuration                                `aper:"valueExt,optional"`
	M5Configuration                   *M5Configuration                                `aper:"valueExt,optional"`
	M6Configuration                   *M6Configuration                                `aper:"valueExt,optional"`
	M7Configuration                   *M7Configuration                                `aper:"valueExt,optional"`
	BluetoothMeasurementConfiguration *BluetoothMeasurementConfiguration              `aper:"valueExt,optional"`
	WLANMeasurementConfiguration      *WLANMeasurementConfiguration                   `aper:"valueExt,optional"`
	MDTLocationInfo                   *MDTLocationInfo                                `aper:"valueExt,optional"`
	SensorMeasurementConfiguration    *SensorMeasurementConfiguration                 `aper:"valueExt,optional"`
	IEExtensions                      *ProtocolExtensionContainerImmediateMDTNrExtIEs `aper:"optional"`
}
