// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-PDU-Descriptions" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

const (
	InitiatingMessagePresentNothing int = iota /* No components present */
	InitiatingMessagePresentAMFConfigurationUpdate
	InitiatingMessagePresentBroadcastSessionModification
	InitiatingMessagePresentBroadcastSessionRelease
	InitiatingMessagePresentBroadcastSessionSetup
	InitiatingMessagePresentBroadcastSessionTransport
	InitiatingMessagePresentDistributionSetup
	InitiatingMessagePresentDistributionRelease
	InitiatingMessagePresentHandoverCancel
	InitiatingMessagePresentHandoverPreparation
	InitiatingMessagePresentHandoverResourceAllocation
	InitiatingMessagePresentInitialContextSetup
	InitiatingMessagePresentMTCommunicationHandling
	InitiatingMessagePresentMulticastSessionActivation
	InitiatingMessagePresentMulticastSessionDeactivation
	InitiatingMessagePresentMulticastSessionUpdate
	InitiatingMessagePresentNGReset
	InitiatingMessagePresentNGSetup
	InitiatingMessagePresentPathSwitchRequest
	InitiatingMessagePresentPDUSessionResourceModify
	InitiatingMessagePresentPDUSessionResourceModifyIndication
	InitiatingMessagePresentPDUSessionResourceRelease
	InitiatingMessagePresentPDUSessionResourceSetup
	InitiatingMessagePresentPWSCancel
	InitiatingMessagePresentRANConfigurationUpdate
	InitiatingMessagePresentTimingSynchronisationStatus
	InitiatingMessagePresentUEContextModification
	InitiatingMessagePresentUEContextRelease
	InitiatingMessagePresentUEContextResume
	InitiatingMessagePresentUEContextSuspend
	InitiatingMessagePresentUERadioCapabilityCheck
	InitiatingMessagePresentUERadioCapabilityIDMapping
	InitiatingMessagePresentWriteReplaceWarning
	InitiatingMessagePresentAMFCPRelocationIndication
	InitiatingMessagePresentAMFStatusIndication
	InitiatingMessagePresentBroadcastSessionReleaseRequired
	InitiatingMessagePresentCellTrafficTrace
	InitiatingMessagePresentConnectionEstablishmentIndication
	InitiatingMessagePresentDeactivateTrace
	InitiatingMessagePresentDownlinkNASTransport
	InitiatingMessagePresentDownlinkNonUEAssociatedNRPPaTransport
	InitiatingMessagePresentDownlinkRANConfigurationTransfer
	InitiatingMessagePresentDownlinkRANEarlyStatusTransfer
	InitiatingMessagePresentDownlinkRANStatusTransfer
	InitiatingMessagePresentDownlinkRIMInformationTransfer
	InitiatingMessagePresentDownlinkUEAssociatedNRPPaTransport
	InitiatingMessagePresentErrorIndication
	InitiatingMessagePresentHandoverNotification
	InitiatingMessagePresentHandoverSuccess
	InitiatingMessagePresentInitialUEMessage
	InitiatingMessagePresentLocationReport
	InitiatingMessagePresentLocationReportingControl
	InitiatingMessagePresentLocationReportingFailureIndication
	InitiatingMessagePresentMulticastGroupPaging
	InitiatingMessagePresentNASNonDeliveryIndication
	InitiatingMessagePresentOverloadStart
	InitiatingMessagePresentOverloadStop
	InitiatingMessagePresentPaging
	InitiatingMessagePresentPDUSessionResourceNotify
	InitiatingMessagePresentPrivateMessage
	InitiatingMessagePresentPWSFailureIndication
	InitiatingMessagePresentPWSRestartIndication
	InitiatingMessagePresentRANCPRelocationIndication
	InitiatingMessagePresentRANPagingRequest
	InitiatingMessagePresentRerouteNASRequest
	InitiatingMessagePresentRetrieveUEInformation
	InitiatingMessagePresentRRCInactiveTransitionReport
	InitiatingMessagePresentSecondaryRATDataUsageReport
	InitiatingMessagePresentTimingSynchronisationStatusReport
	InitiatingMessagePresentTraceFailureIndication
	InitiatingMessagePresentTraceStart
	InitiatingMessagePresentUEContextReleaseRequest
	InitiatingMessagePresentUEInformationTransfer
	InitiatingMessagePresentUERadioCapabilityInfoIndication
	InitiatingMessagePresentUETNLABindingRelease
	InitiatingMessagePresentUplinkNASTransport
	InitiatingMessagePresentUplinkNonUEAssociatedNRPPaTransport
	InitiatingMessagePresentUplinkRANConfigurationTransfer
	InitiatingMessagePresentUplinkRANEarlyStatusTransfer
	InitiatingMessagePresentUplinkRANStatusTransfer
	InitiatingMessagePresentUplinkRIMInformationTransfer
	InitiatingMessagePresentUplinkUEAssociatedNRPPaTransport
)

type InitiatingMessage struct {
	ProcedureCode ProcedureCode
	Criticality   Criticality
	Value         InitiatingMessageValue `aper:"openType,referenceFieldName:ProcedureCode"`
}

type InitiatingMessageValue struct {
	Present                               int
	AMFConfigurationUpdate                *AMFConfigurationUpdate                `aper:"referenceFieldValue:0,valueExt"`
	BroadcastSessionModification          *BroadcastSessionModificationRequest   `aper:"referenceFieldValue:66,valueExt"`
	BroadcastSessionRelease               *BroadcastSessionReleaseRequest        `aper:"referenceFieldValue:67,valueExt"`
	BroadcastSessionSetup                 *BroadcastSessionSetupRequest          `aper:"referenceFieldValue:68,valueExt"`
	BroadcastSessionTransport             *BroadcastSessionTransportRequest      `aper:"referenceFieldValue:80,valueExt"`
	DistributionSetup                     *DistributionSetupRequest              `aper:"referenceFieldValue:69,valueExt"`
	DistributionRelease                   *DistributionReleaseRequest            `aper:"referenceFieldValue:70,valueExt"`
	HandoverCancel                        *HandoverCancel                        `aper:"referenceFieldValue:10,valueExt"`
	HandoverPreparation                   *HandoverRequired                      `aper:"referenceFieldValue:12,valueExt"`
	HandoverResourceAllocation            *HandoverRequest                       `aper:"referenceFieldValue:13,valueExt"`
	InitialContextSetup                   *InitialContextSetupRequest            `aper:"referenceFieldValue:14,valueExt"`
	MTCommunicationHandling               *MTCommunicationHandlingRequest        `aper:"referenceFieldValue:78,valueExt"`
	MulticastSessionActivation            *MulticastSessionActivationRequest     `aper:"referenceFieldValue:71,valueExt"`
	MulticastSessionDeactivation          *MulticastSessionDeactivationRequest   `aper:"referenceFieldValue:72,valueExt"`
	MulticastSessionUpdate                *MulticastSessionUpdateRequest         `aper:"referenceFieldValue:73,valueExt"`
	NGReset                               *NGReset                               `aper:"referenceFieldValue:20,valueExt"`
	NGSetup                               *NGSetupRequest                        `aper:"referenceFieldValue:21,valueExt"`
	PathSwitchRequest                     *PathSwitchRequest                     `aper:"referenceFieldValue:25,valueExt"`
	PDUSessionResourceModify              *PDUSessionResourceModifyRequest       `aper:"referenceFieldValue:26,valueExt"`
	PDUSessionResourceModifyIndication    *PDUSessionResourceModifyIndication    `aper:"referenceFieldValue:27,valueExt"`
	PDUSessionResourceRelease             *PDUSessionResourceReleaseCommand      `aper:"referenceFieldValue:28,valueExt"`
	PDUSessionResourceSetup               *PDUSessionResourceSetupRequest        `aper:"referenceFieldValue:29,valueExt"`
	PWSCancel                             *PWSCancelRequest                      `aper:"referenceFieldValue:32,valueExt"`
	RANConfigurationUpdate                *RANConfigurationUpdate                `aper:"referenceFieldValue:35,valueExt"`
	TimingSynchronisationStatus           *TimingSynchronisationStatusRequest    `aper:"referenceFieldValue:76,valueExt"`
	UEContextModification                 *UEContextModificationRequest          `aper:"referenceFieldValue:40,valueExt"`
	UEContextRelease                      *UEContextReleaseCommand               `aper:"referenceFieldValue:41,valueExt"`
	UEContextResume                       *UEContextResumeRequest                `aper:"referenceFieldValue:58,valueExt"`
	UEContextSuspend                      *UEContextSuspendRequest               `aper:"referenceFieldValue:59,valueExt"`
	UERadioCapabilityCheck                *UERadioCapabilityCheckRequest         `aper:"referenceFieldValue:43,valueExt"`
	UERadioCapabilityIDMapping            *UERadioCapabilityIDMappingRequest     `aper:"referenceFieldValue:60,valueExt"`
	WriteReplaceWarning                   *WriteReplaceWarningRequest            `aper:"referenceFieldValue:51,valueExt"`
	AMFCPRelocationIndication             *AMFCPRelocationIndication             `aper:"referenceFieldValue:64,valueExt"`
	AMFStatusIndication                   *AMFStatusIndication                   `aper:"referenceFieldValue:1,valueExt"`
	BroadcastSessionReleaseRequired       *BroadcastSessionReleaseRequired       `aper:"referenceFieldValue:75,valueExt"`
	CellTrafficTrace                      *CellTrafficTrace                      `aper:"referenceFieldValue:2,valueExt"`
	ConnectionEstablishmentIndication     *ConnectionEstablishmentIndication     `aper:"referenceFieldValue:65,valueExt"`
	DeactivateTrace                       *DeactivateTrace                       `aper:"referenceFieldValue:3,valueExt"`
	DownlinkNASTransport                  *DownlinkNASTransport                  `aper:"referenceFieldValue:4,valueExt"`
	DownlinkNonUEAssociatedNRPPaTransport *DownlinkNonUEAssociatedNRPPaTransport `aper:"referenceFieldValue:5,valueExt"`
	DownlinkRANConfigurationTransfer      *DownlinkRANConfigurationTransfer      `aper:"referenceFieldValue:6,valueExt"`
	DownlinkRANEarlyStatusTransfer        *DownlinkRANEarlyStatusTransfer        `aper:"referenceFieldValue:63,valueExt"`
	DownlinkRANStatusTransfer             *DownlinkRANStatusTransfer             `aper:"referenceFieldValue:7,valueExt"`
	DownlinkRIMInformationTransfer        *DownlinkRIMInformationTransfer        `aper:"referenceFieldValue:54,valueExt"`
	DownlinkUEAssociatedNRPPaTransport    *DownlinkUEAssociatedNRPPaTransport    `aper:"referenceFieldValue:8,valueExt"`
	ErrorIndication                       *ErrorIndication                       `aper:"referenceFieldValue:9,valueExt"`
	HandoverNotification                  *HandoverNotify                        `aper:"referenceFieldValue:11,valueExt"`
	HandoverSuccess                       *HandoverSuccess                       `aper:"referenceFieldValue:61,valueExt"`
	InitialUEMessage                      *InitialUEMessage                      `aper:"referenceFieldValue:15,valueExt"`
	LocationReport                        *LocationReport                        `aper:"referenceFieldValue:18,valueExt"`
	LocationReportingControl              *LocationReportingControl              `aper:"referenceFieldValue:16,valueExt"`
	LocationReportingFailureIndication    *LocationReportingFailureIndication    `aper:"referenceFieldValue:17,valueExt"`
	MulticastGroupPaging                  *MulticastGroupPaging                  `aper:"referenceFieldValue:74,valueExt"`
	NASNonDeliveryIndication              *NASNonDeliveryIndication              `aper:"referenceFieldValue:19,valueExt"`
	OverloadStart                         *OverloadStart                         `aper:"referenceFieldValue:22,valueExt"`
	OverloadStop                          *OverloadStop                          `aper:"referenceFieldValue:23,valueExt"`
	Paging                                *Paging                                `aper:"referenceFieldValue:24,valueExt"`
	PDUSessionResourceNotify              *PDUSessionResourceNotify              `aper:"referenceFieldValue:30,valueExt"`
	PrivateMessage                        *PrivateMessage                        `aper:"referenceFieldValue:31,valueExt"`
	PWSFailureIndication                  *PWSFailureIndication                  `aper:"referenceFieldValue:33,valueExt"`
	PWSRestartIndication                  *PWSRestartIndication                  `aper:"referenceFieldValue:34,valueExt"`
	RANCPRelocationIndication             *RANCPRelocationIndication             `aper:"referenceFieldValue:57,valueExt"`
	RANPagingRequest                      *RANPagingRequest                      `aper:"referenceFieldValue:79,valueExt"`
	RerouteNASRequest                     *RerouteNASRequest                     `aper:"referenceFieldValue:36,valueExt"`
	RetrieveUEInformation                 *RetrieveUEInformation                 `aper:"referenceFieldValue:55,valueExt"`
	RRCInactiveTransitionReport           *RRCInactiveTransitionReport           `aper:"referenceFieldValue:37,valueExt"`
	SecondaryRATDataUsageReport           *SecondaryRATDataUsageReport           `aper:"referenceFieldValue:52,valueExt"`
	TimingSynchronisationStatusReport     *TimingSynchronisationStatusReport     `aper:"referenceFieldValue:77,valueExt"`
	TraceFailureIndication                *TraceFailureIndication                `aper:"referenceFieldValue:38,valueExt"`
	TraceStart                            *TraceStart                            `aper:"referenceFieldValue:39,valueExt"`
	UEContextReleaseRequest               *UEContextReleaseRequest               `aper:"referenceFieldValue:42,valueExt"`
	UEInformationTransfer                 *UEInformationTransfer                 `aper:"referenceFieldValue:56,valueExt"`
	UERadioCapabilityInfoIndication       *UERadioCapabilityInfoIndication       `aper:"referenceFieldValue:44,valueExt"`
	UETNLABindingRelease                  *UETNLABindingReleaseRequest           `aper:"referenceFieldValue:45,valueExt"`
	UplinkNASTransport                    *UplinkNASTransport                    `aper:"referenceFieldValue:46,valueExt"`
	UplinkNonUEAssociatedNRPPaTransport   *UplinkNonUEAssociatedNRPPaTransport   `aper:"referenceFieldValue:47,valueExt"`
	UplinkRANConfigurationTransfer        *UplinkRANConfigurationTransfer        `aper:"referenceFieldValue:48,valueExt"`
	UplinkRANEarlyStatusTransfer          *UplinkRANEarlyStatusTransfer          `aper:"referenceFieldValue:62,valueExt"`
	UplinkRANStatusTransfer               *UplinkRANStatusTransfer               `aper:"referenceFieldValue:49,valueExt"`
	UplinkRIMInformationTransfer          *UplinkRIMInformationTransfer          `aper:"referenceFieldValue:53,valueExt"`
	UplinkUEAssociatedNRPPaTransport      *UplinkUEAssociatedNRPPaTransport      `aper:"referenceFieldValue:50,valueExt"`
}
