// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	LoggingDurationPresentM10  aper.Enumerated = 0
	LoggingDurationPresentM20  aper.Enumerated = 1
	LoggingDurationPresentM40  aper.Enumerated = 2
	LoggingDurationPresentM60  aper.Enumerated = 3
	LoggingDurationPresentM90  aper.Enumerated = 4
	LoggingDurationPresentM120 aper.Enumerated = 5
)

type LoggingDuration struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:5"`
}
