// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	LoggingIntervalPresentMs320    aper.Enumerated = 0
	LoggingIntervalPresentMs640    aper.Enumerated = 1
	LoggingIntervalPresentMs1280   aper.Enumerated = 2
	LoggingIntervalPresentMs2560   aper.Enumerated = 3
	LoggingIntervalPresentMs5120   aper.Enumerated = 4
	LoggingIntervalPresentMs10240  aper.Enumerated = 5
	LoggingIntervalPresentMs20480  aper.Enumerated = 6
	LoggingIntervalPresentMs30720  aper.Enumerated = 7
	LoggingIntervalPresentMs40960  aper.Enumerated = 8
	LoggingIntervalPresentMs61440  aper.Enumerated = 9
	LoggingIntervalPresentInfinity aper.Enumerated = 10
)

type LoggingInterval struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:10"`
}
