// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

type M1Configuration struct {
	M1reportingTrigger  M1ReportingTrigger
	M1thresholdEventA2  *M1ThresholdEventA2                              `aper:"valueExt,optional"`
	M1periodicReporting *M1PeriodicReporting                             `aper:"valueExt,optional"`
	IEExtensions        *ProtocolExtensionContainerM1ConfigurationExtIEs `aper:"optional"`
}
