// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

const (
	M1ThresholdTypePresentNothing int = iota /* No components present */
	M1ThresholdTypePresentThresholdRSRP
	M1ThresholdTypePresentThresholdRSRQ
	M1ThresholdTypePresentThresholdSINR
	M1ThresholdTypePresentChoiceExtensions
)

type M1ThresholdType struct {
	Present          int
	ThresholdRSRP    *ThresholdRSRP
	ThresholdRSRQ    *ThresholdRSRQ
	ThresholdSINR    *ThresholdSINR
	ChoiceExtensions *M1ThresholdTypeExtIEs
}
