// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	M5periodPresentMs1024  aper.Enumerated = 0
	M5periodPresentMs2048  aper.Enumerated = 1
	M5periodPresentMs5120  aper.Enumerated = 2
	M5periodPresentMs10240 aper.Enumerated = 3
	M5periodPresentMin1    aper.Enumerated = 4
)

type M5period struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:4"`
}
