// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	M6reportIntervalPresentMs120   aper.Enumerated = 0
	M6reportIntervalPresentMs240   aper.Enumerated = 1
	M6reportIntervalPresentMs480   aper.Enumerated = 2
	M6reportIntervalPresentMs640   aper.Enumerated = 3
	M6reportIntervalPresentMs1024  aper.Enumerated = 4
	M6reportIntervalPresentMs2048  aper.Enumerated = 5
	M6reportIntervalPresentMs5120  aper.Enumerated = 6
	M6reportIntervalPresentMs10240 aper.Enumerated = 7
	M6reportIntervalPresentMs20480 aper.Enumerated = 8
	M6reportIntervalPresentMs40960 aper.Enumerated = 9
	M6reportIntervalPresentMin1    aper.Enumerated = 10
	M6reportIntervalPresentMin6    aper.Enumerated = 11
	M6reportIntervalPresentMin12   aper.Enumerated = 12
	M6reportIntervalPresentMin30   aper.Enumerated = 13
)

type M6reportInterval struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:13"`
}
