// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	M7ReportAmountMDTPresentR1       aper.Enumerated = 0
	M7ReportAmountMDTPresentR2       aper.Enumerated = 1
	M7ReportAmountMDTPresentR4       aper.Enumerated = 2
	M7ReportAmountMDTPresentR8       aper.Enumerated = 3
	M7ReportAmountMDTPresentR16      aper.Enumerated = 4
	M7ReportAmountMDTPresentR32      aper.Enumerated = 5
	M7ReportAmountMDTPresentR64      aper.Enumerated = 6
	M7ReportAmountMDTPresentInfinity aper.Enumerated = 7
)

type M7ReportAmountMDT struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:7"`
}
