// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

const (
	MeasurementThresholdL1LoggedMDTPresentNothing int = iota /* No components present */
	MeasurementThresholdL1LoggedMDTPresentThresholdRSRP
	MeasurementThresholdL1LoggedMDTPresentThresholdRSRQ
	MeasurementThresholdL1LoggedMDTPresentChoiceExtensions
)

type MeasurementThresholdL1LoggedMDT struct {
	Present          int
	ThresholdRSRP    *ThresholdRSRP
	ThresholdRSRQ    *ThresholdRSRQ
	ChoiceExtensions *MeasurementThresholdL1LoggedMDTExtIEs
}
