// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

const (
	MRBProgressInformationPresentNothing int = iota /* No components present */
	MRBProgressInformationPresentPDCPSNLength12
	MRBProgressInformationPresentPDCPSNLength18
	MRBProgressInformationPresentChoiceExtensions
)

type MRBProgressInformation struct {
	Present          int
	PDCPSNLength12   *int64 `aper:"valueLB:0,valueUB:4095"`
	PDCPSNLength18   *int64 `aper:"valueLB:0,valueUB:262143"`
	ChoiceExtensions *MRBProgressInformationExtIEs
}
