// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	NBIoTPagingDRXPresentRf32   aper.Enumerated = 0
	NBIoTPagingDRXPresentRf64   aper.Enumerated = 1
	NBIoTPagingDRXPresentRf128  aper.Enumerated = 2
	NBIoTPagingDRXPresentRf256  aper.Enumerated = 3
	NBIoTPagingDRXPresentRf512  aper.Enumerated = 4
	NBIoTPagingDRXPresentRf1024 aper.Enumerated = 5
)

type NBIoTPagingDRX struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:5"`
}
