// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	NBIoTPagingTimeWindowPresentS1  aper.Enumerated = 0
	NBIoTPagingTimeWindowPresentS2  aper.Enumerated = 1
	NBIoTPagingTimeWindowPresentS3  aper.Enumerated = 2
	NBIoTPagingTimeWindowPresentS4  aper.Enumerated = 3
	NBIoTPagingTimeWindowPresentS5  aper.Enumerated = 4
	NBIoTPagingTimeWindowPresentS6  aper.Enumerated = 5
	NBIoTPagingTimeWindowPresentS7  aper.Enumerated = 6
	NBIoTPagingTimeWindowPresentS8  aper.Enumerated = 7
	NBIoTPagingTimeWindowPresentS9  aper.Enumerated = 8
	NBIoTPagingTimeWindowPresentS10 aper.Enumerated = 9
	NBIoTPagingTimeWindowPresentS11 aper.Enumerated = 10
	NBIoTPagingTimeWindowPresentS12 aper.Enumerated = 11
	NBIoTPagingTimeWindowPresentS13 aper.Enumerated = 12
	NBIoTPagingTimeWindowPresentS14 aper.Enumerated = 13
	NBIoTPagingTimeWindowPresentS15 aper.Enumerated = 14
	NBIoTPagingTimeWindowPresentS16 aper.Enumerated = 15
)

type NBIoTPagingTimeWindow struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:15"`
}
