// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	NBIoTPagingEDRXCyclePresentHf2    aper.Enumerated = 0
	NBIoTPagingEDRXCyclePresentHf4    aper.Enumerated = 1
	NBIoTPagingEDRXCyclePresentHf6    aper.Enumerated = 2
	NBIoTPagingEDRXCyclePresentHf8    aper.Enumerated = 3
	NBIoTPagingEDRXCyclePresentHf10   aper.Enumerated = 4
	NBIoTPagingEDRXCyclePresentHf12   aper.Enumerated = 5
	NBIoTPagingEDRXCyclePresentHf14   aper.Enumerated = 6
	NBIoTPagingEDRXCyclePresentHf16   aper.Enumerated = 7
	NBIoTPagingEDRXCyclePresentHf32   aper.Enumerated = 8
	NBIoTPagingEDRXCyclePresentHf64   aper.Enumerated = 9
	NBIoTPagingEDRXCyclePresentHf128  aper.Enumerated = 10
	NBIoTPagingEDRXCyclePresentHf256  aper.Enumerated = 11
	NBIoTPagingEDRXCyclePresentHf512  aper.Enumerated = 12
	NBIoTPagingEDRXCyclePresentHf1024 aper.Enumerated = 13
)

type NBIoTPagingEDRXCycle struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:13"`
}
