// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

type NGRANCellReportItem struct {
	NGRANCGI                             NGRANCGI                                             `aper:"valueLB:0,valueUB:2"`
	NGRANCompositeAvailableCapacityGroup EUTRANCompositeAvailableCapacityGroup                `aper:"valueExt"`
	NGRANNumberOfActiveUEs               *NGRANNumberOfActiveUEs                              `aper:"optional"`
	NGRANNoofRRCConnections              *NGRANNoofRRCConnections                             `aper:"optional"`
	NGRANRadioResourceStatus             *NGRANRadioResourceStatus                            `aper:"valueExt,optional"`
	IEExtensions                         *ProtocolExtensionContainerNGRANCellReportItemExtIEs `aper:"optional"`
}
