// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	NRPagingLongEDRXCycleForRRCINACTIVEPresentHf2    aper.Enumerated = 0
	NRPagingLongEDRXCycleForRRCINACTIVEPresentHf4    aper.Enumerated = 1
	NRPagingLongEDRXCycleForRRCINACTIVEPresentHf8    aper.Enumerated = 2
	NRPagingLongEDRXCycleForRRCINACTIVEPresentHf16   aper.Enumerated = 3
	NRPagingLongEDRXCycleForRRCINACTIVEPresentHf32   aper.Enumerated = 4
	NRPagingLongEDRXCycleForRRCINACTIVEPresentHf64   aper.Enumerated = 5
	NRPagingLongEDRXCycleForRRCINACTIVEPresentHf128  aper.Enumerated = 6
	NRPagingLongEDRXCycleForRRCINACTIVEPresentHf256  aper.Enumerated = 7
	NRPagingLongEDRXCycleForRRCINACTIVEPresentHf512  aper.Enumerated = 8
	NRPagingLongEDRXCycleForRRCINACTIVEPresentHf1024 aper.Enumerated = 9
)

type NRPagingLongEDRXCycleForRRCINACTIVE struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:9"`
}
