// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	NRPagingTimeWindowForRRCINACTIVEPresentS1  aper.Enumerated = 0
	NRPagingTimeWindowForRRCINACTIVEPresentS2  aper.Enumerated = 1
	NRPagingTimeWindowForRRCINACTIVEPresentS3  aper.Enumerated = 2
	NRPagingTimeWindowForRRCINACTIVEPresentS4  aper.Enumerated = 3
	NRPagingTimeWindowForRRCINACTIVEPresentS5  aper.Enumerated = 4
	NRPagingTimeWindowForRRCINACTIVEPresentS6  aper.Enumerated = 5
	NRPagingTimeWindowForRRCINACTIVEPresentS7  aper.Enumerated = 6
	NRPagingTimeWindowForRRCINACTIVEPresentS8  aper.Enumerated = 7
	NRPagingTimeWindowForRRCINACTIVEPresentS9  aper.Enumerated = 8
	NRPagingTimeWindowForRRCINACTIVEPresentS10 aper.Enumerated = 9
	NRPagingTimeWindowForRRCINACTIVEPresentS11 aper.Enumerated = 10
	NRPagingTimeWindowForRRCINACTIVEPresentS12 aper.Enumerated = 11
	NRPagingTimeWindowForRRCINACTIVEPresentS13 aper.Enumerated = 12
	NRPagingTimeWindowForRRCINACTIVEPresentS14 aper.Enumerated = 13
	NRPagingTimeWindowForRRCINACTIVEPresentS15 aper.Enumerated = 14
	NRPagingTimeWindowForRRCINACTIVEPresentS16 aper.Enumerated = 15
	NRPagingTimeWindowForRRCINACTIVEPresentS17 aper.Enumerated = 16
	NRPagingTimeWindowForRRCINACTIVEPresentS18 aper.Enumerated = 17
	NRPagingTimeWindowForRRCINACTIVEPresentS19 aper.Enumerated = 18
	NRPagingTimeWindowForRRCINACTIVEPresentS20 aper.Enumerated = 19
	NRPagingTimeWindowForRRCINACTIVEPresentS21 aper.Enumerated = 20
	NRPagingTimeWindowForRRCINACTIVEPresentS22 aper.Enumerated = 21
	NRPagingTimeWindowForRRCINACTIVEPresentS23 aper.Enumerated = 22
	NRPagingTimeWindowForRRCINACTIVEPresentS24 aper.Enumerated = 23
	NRPagingTimeWindowForRRCINACTIVEPresentS25 aper.Enumerated = 24
	NRPagingTimeWindowForRRCINACTIVEPresentS26 aper.Enumerated = 25
	NRPagingTimeWindowForRRCINACTIVEPresentS27 aper.Enumerated = 26
	NRPagingTimeWindowForRRCINACTIVEPresentS28 aper.Enumerated = 27
	NRPagingTimeWindowForRRCINACTIVEPresentS29 aper.Enumerated = 28
	NRPagingTimeWindowForRRCINACTIVEPresentS30 aper.Enumerated = 29
	NRPagingTimeWindowForRRCINACTIVEPresentS31 aper.Enumerated = 30
	NRPagingTimeWindowForRRCINACTIVEPresentS32 aper.Enumerated = 31
)

type NRPagingTimeWindowForRRCINACTIVE struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:31"`
}
