// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	NRPagingTimeWindowPresentS1  aper.Enumerated = 0
	NRPagingTimeWindowPresentS2  aper.Enumerated = 1
	NRPagingTimeWindowPresentS3  aper.Enumerated = 2
	NRPagingTimeWindowPresentS4  aper.Enumerated = 3
	NRPagingTimeWindowPresentS5  aper.Enumerated = 4
	NRPagingTimeWindowPresentS6  aper.Enumerated = 5
	NRPagingTimeWindowPresentS7  aper.Enumerated = 6
	NRPagingTimeWindowPresentS8  aper.Enumerated = 7
	NRPagingTimeWindowPresentS9  aper.Enumerated = 8
	NRPagingTimeWindowPresentS10 aper.Enumerated = 9
	NRPagingTimeWindowPresentS11 aper.Enumerated = 10
	NRPagingTimeWindowPresentS12 aper.Enumerated = 11
	NRPagingTimeWindowPresentS13 aper.Enumerated = 12
	NRPagingTimeWindowPresentS14 aper.Enumerated = 13
	NRPagingTimeWindowPresentS15 aper.Enumerated = 14
	NRPagingTimeWindowPresentS16 aper.Enumerated = 15
	NRPagingTimeWindowPresentS17 aper.Enumerated = 16
	NRPagingTimeWindowPresentS18 aper.Enumerated = 17
	NRPagingTimeWindowPresentS19 aper.Enumerated = 18
	NRPagingTimeWindowPresentS20 aper.Enumerated = 19
	NRPagingTimeWindowPresentS21 aper.Enumerated = 20
	NRPagingTimeWindowPresentS22 aper.Enumerated = 21
	NRPagingTimeWindowPresentS23 aper.Enumerated = 22
	NRPagingTimeWindowPresentS24 aper.Enumerated = 23
	NRPagingTimeWindowPresentS25 aper.Enumerated = 24
	NRPagingTimeWindowPresentS26 aper.Enumerated = 25
	NRPagingTimeWindowPresentS27 aper.Enumerated = 26
	NRPagingTimeWindowPresentS28 aper.Enumerated = 27
	NRPagingTimeWindowPresentS29 aper.Enumerated = 28
	NRPagingTimeWindowPresentS30 aper.Enumerated = 29
	NRPagingTimeWindowPresentS31 aper.Enumerated = 30
	NRPagingTimeWindowPresentS32 aper.Enumerated = 31
)

type NRPagingTimeWindow struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:15"`
}
