// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	NRPagingEDRXCyclePresentHfquarter aper.Enumerated = 0
	NRPagingEDRXCyclePresentHfhalf    aper.Enumerated = 1
	NRPagingEDRXCyclePresentHf1       aper.Enumerated = 2
	NRPagingEDRXCyclePresentHf2       aper.Enumerated = 3
	NRPagingEDRXCyclePresentHf4       aper.Enumerated = 4
	NRPagingEDRXCyclePresentHf8       aper.Enumerated = 5
	NRPagingEDRXCyclePresentHf16      aper.Enumerated = 6
	NRPagingEDRXCyclePresentHf32      aper.Enumerated = 7
	NRPagingEDRXCyclePresentHf64      aper.Enumerated = 8
	NRPagingEDRXCyclePresentHf128     aper.Enumerated = 9
	NRPagingEDRXCyclePresentHf256     aper.Enumerated = 10
	NRPagingEDRXCyclePresentHf512     aper.Enumerated = 11
	NRPagingEDRXCyclePresentHf1024    aper.Enumerated = 12
)

type NRPagingEDRXCycle struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:12"`
}
