// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	NumberOfMeasurementReportingLevelsPresentN2  aper.Enumerated = 0
	NumberOfMeasurementReportingLevelsPresentN3  aper.Enumerated = 1
	NumberOfMeasurementReportingLevelsPresentN4  aper.Enumerated = 2
	NumberOfMeasurementReportingLevelsPresentN5  aper.Enumerated = 3
	NumberOfMeasurementReportingLevelsPresentN10 aper.Enumerated = 4
	NumberOfMeasurementReportingLevelsPresentN0  aper.Enumerated = 5
)

type NumberOfMeasurementReportingLevels struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:4"`
}
