// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	PagingPriorityPresentPriolevel1 aper.Enumerated = 0
	PagingPriorityPresentPriolevel2 aper.Enumerated = 1
	PagingPriorityPresentPriolevel3 aper.Enumerated = 2
	PagingPriorityPresentPriolevel4 aper.Enumerated = 3
	PagingPriorityPresentPriolevel5 aper.Enumerated = 4
	PagingPriorityPresentPriolevel6 aper.Enumerated = 5
	PagingPriorityPresentPriolevel7 aper.Enumerated = 6
	PagingPriorityPresentPriolevel8 aper.Enumerated = 7
)

type PagingPriority struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:7"`
}
