// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	PagingProbabilityInformationPresentP00  aper.Enumerated = 0
	PagingProbabilityInformationPresentP05  aper.Enumerated = 1
	PagingProbabilityInformationPresentP10  aper.Enumerated = 2
	PagingProbabilityInformationPresentP15  aper.Enumerated = 3
	PagingProbabilityInformationPresentP20  aper.Enumerated = 4
	PagingProbabilityInformationPresentP25  aper.Enumerated = 5
	PagingProbabilityInformationPresentP30  aper.Enumerated = 6
	PagingProbabilityInformationPresentP35  aper.Enumerated = 7
	PagingProbabilityInformationPresentP40  aper.Enumerated = 8
	PagingProbabilityInformationPresentP45  aper.Enumerated = 9
	PagingProbabilityInformationPresentP50  aper.Enumerated = 10
	PagingProbabilityInformationPresentP55  aper.Enumerated = 11
	PagingProbabilityInformationPresentP60  aper.Enumerated = 12
	PagingProbabilityInformationPresentP65  aper.Enumerated = 13
	PagingProbabilityInformationPresentP70  aper.Enumerated = 14
	PagingProbabilityInformationPresentP75  aper.Enumerated = 15
	PagingProbabilityInformationPresentP80  aper.Enumerated = 16
	PagingProbabilityInformationPresentP85  aper.Enumerated = 17
	PagingProbabilityInformationPresentP90  aper.Enumerated = 18
	PagingProbabilityInformationPresentP95  aper.Enumerated = 19
	PagingProbabilityInformationPresentP100 aper.Enumerated = 20
)

type PagingProbabilityInformation struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:20"`
}
