// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

type PagingPolicyDifferentiationItem struct {
	QosFlowIdentifier              *QosFlowIdentifier                                               `aper:"optional"`
	PagingPolicyIndicator          *PagingPolicyIndicator                                           `aper:"optional"`
	AllocationAndRetentionPriority *AllocationAndRetentionPriority                                  `aper:"valueExt,optional"`
	FiveQI                         *FiveQI                                                          `aper:"optional"`
	DlDataSize                     *int64                                                           `aper:"optional,valueExt,valueLB:0,valueUB:96000"`
	IEExtensions                   *ProtocolExtensionContainerPagingPolicyDifferentiationItemExtIEs `aper:"optional"`
}
