// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	ParentTImeSourcePresentSynce            aper.Enumerated = 0
	ParentTImeSourcePresentPtp              aper.Enumerated = 1
	ParentTImeSourcePresentGnss             aper.Enumerated = 2
	ParentTImeSourcePresentAtomicclock      aper.Enumerated = 3
	ParentTImeSourcePresentTerrestrialradio aper.Enumerated = 4
	ParentTImeSourcePresentSerialtimecode   aper.Enumerated = 5
	ParentTImeSourcePresentNtp              aper.Enumerated = 6
	ParentTImeSourcePresentHandset          aper.Enumerated = 7
	ParentTImeSourcePresentOther            aper.Enumerated = 8
)

type ParentTImeSource struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:8"`
}
