// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-CommonDataTypes" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"fmt"
)

const (
	ProcedureCodeAMFConfigurationUpdate                int64 = 0
	ProcedureCodeAMFStatusIndication                   int64 = 1
	ProcedureCodeCellTrafficTrace                      int64 = 2
	ProcedureCodeDeactivateTrace                       int64 = 3
	ProcedureCodeDownlinkNASTransport                  int64 = 4
	ProcedureCodeDownlinkNonUEAssociatedNRPPaTransport int64 = 5
	ProcedureCodeDownlinkRANConfigurationTransfer      int64 = 6
	ProcedureCodeDownlinkRANStatusTransfer             int64 = 7
	ProcedureCodeDownlinkUEAssociatedNRPPaTransport    int64 = 8
	ProcedureCodeErrorIndication                       int64 = 9
	ProcedureCodeHandoverCancel                        int64 = 10
	ProcedureCodeHandoverNotification                  int64 = 11
	ProcedureCodeHandoverPreparation                   int64 = 12
	ProcedureCodeHandoverResourceAllocation            int64 = 13
	ProcedureCodeInitialContextSetup                   int64 = 14
	ProcedureCodeInitialUEMessage                      int64 = 15
	ProcedureCodeLocationReportingControl              int64 = 16
	ProcedureCodeLocationReportingFailureIndication    int64 = 17
	ProcedureCodeLocationReport                        int64 = 18
	ProcedureCodeNASNonDeliveryIndication              int64 = 19
	ProcedureCodeNGReset                               int64 = 20
	ProcedureCodeNGSetup                               int64 = 21
	ProcedureCodeOverloadStart                         int64 = 22
	ProcedureCodeOverloadStop                          int64 = 23
	ProcedureCodePaging                                int64 = 24
	ProcedureCodePathSwitchRequest                     int64 = 25
	ProcedureCodePDUSessionResourceModify              int64 = 26
	ProcedureCodePDUSessionResourceModifyIndication    int64 = 27
	ProcedureCodePDUSessionResourceRelease             int64 = 28
	ProcedureCodePDUSessionResourceSetup               int64 = 29
	ProcedureCodePDUSessionResourceNotify              int64 = 30
	ProcedureCodePrivateMessage                        int64 = 31
	ProcedureCodePWSCancel                             int64 = 32
	ProcedureCodePWSFailureIndication                  int64 = 33
	ProcedureCodePWSRestartIndication                  int64 = 34
	ProcedureCodeRANConfigurationUpdate                int64 = 35
	ProcedureCodeRerouteNASRequest                     int64 = 36
	ProcedureCodeRRCInactiveTransitionReport           int64 = 37
	ProcedureCodeTraceFailureIndication                int64 = 38
	ProcedureCodeTraceStart                            int64 = 39
	ProcedureCodeUEContextModification                 int64 = 40
	ProcedureCodeUEContextRelease                      int64 = 41
	ProcedureCodeUEContextReleaseRequest               int64 = 42
	ProcedureCodeUERadioCapabilityCheck                int64 = 43
	ProcedureCodeUERadioCapabilityInfoIndication       int64 = 44
	ProcedureCodeUETNLABindingRelease                  int64 = 45
	ProcedureCodeUplinkNASTransport                    int64 = 46
	ProcedureCodeUplinkNonUEAssociatedNRPPaTransport   int64 = 47
	ProcedureCodeUplinkRANConfigurationTransfer        int64 = 48
	ProcedureCodeUplinkRANStatusTransfer               int64 = 49
	ProcedureCodeUplinkUEAssociatedNRPPaTransport      int64 = 50
	ProcedureCodeWriteReplaceWarning                   int64 = 51
	ProcedureCodeSecondaryRATDataUsageReport           int64 = 52
	ProcedureCodeUplinkRIMInformationTransfer          int64 = 53
	ProcedureCodeDownlinkRIMInformationTransfer        int64 = 54
	ProcedureCodeRetrieveUEInformation                 int64 = 55
	ProcedureCodeUEInformationTransfer                 int64 = 56
	ProcedureCodeRANCPRelocationIndication             int64 = 57
	ProcedureCodeUEContextResume                       int64 = 58
	ProcedureCodeUEContextSuspend                      int64 = 59
	ProcedureCodeUERadioCapabilityIDMapping            int64 = 60
	ProcedureCodeHandoverSuccess                       int64 = 61
	ProcedureCodeUplinkRANEarlyStatusTransfer          int64 = 62
	ProcedureCodeDownlinkRANEarlyStatusTransfer        int64 = 63
	ProcedureCodeAMFCPRelocationIndication             int64 = 64
	ProcedureCodeConnectionEstablishmentIndication     int64 = 65
	ProcedureCodeBroadcastSessionModification          int64 = 66
	ProcedureCodeBroadcastSessionRelease               int64 = 67
	ProcedureCodeBroadcastSessionSetup                 int64 = 68
	ProcedureCodeDistributionSetup                     int64 = 69
	ProcedureCodeDistributionRelease                   int64 = 70
	ProcedureCodeMulticastSessionActivation            int64 = 71
	ProcedureCodeMulticastSessionDeactivation          int64 = 72
	ProcedureCodeMulticastSessionUpdate                int64 = 73
	ProcedureCodeMulticastGroupPaging                  int64 = 74
	ProcedureCodeBroadcastSessionReleaseRequired       int64 = 75
	ProcedureCodeTimingSynchronisationStatus           int64 = 76
	ProcedureCodeTimingSynchronisationStatusReport     int64 = 77
	ProcedureCodeMTCommunicationHandling               int64 = 78
	ProcedureCodeRANPagingRequest                      int64 = 79
	ProcedureCodeBroadcastSessionTransport             int64 = 80
)

type ProcedureCode struct {
	Value int64 `aper:"valueLB:0,valueUB:255"`
}

func ProcedureName(code int64) string {
	switch code {
	case ProcedureCodeAMFConfigurationUpdate:
		return "AMFConfigurationUpdate"
	case ProcedureCodeAMFStatusIndication:
		return "AMFStatusIndication"
	case ProcedureCodeCellTrafficTrace:
		return "CellTrafficTrace"
	case ProcedureCodeDeactivateTrace:
		return "DeactivateTrace"
	case ProcedureCodeDownlinkNASTransport:
		return "DownlinkNASTransport"
	case ProcedureCodeDownlinkNonUEAssociatedNRPPaTransport:
		return "DownlinkNonUEAssociatedNRPPaTransport"
	case ProcedureCodeDownlinkRANConfigurationTransfer:
		return "DownlinkRANConfigurationTransfer"
	case ProcedureCodeDownlinkRANStatusTransfer:
		return "DownlinkRANStatusTransfer"
	case ProcedureCodeDownlinkUEAssociatedNRPPaTransport:
		return "DownlinkUEAssociatedNRPPaTransport"
	case ProcedureCodeErrorIndication:
		return "ErrorIndication"
	case ProcedureCodeHandoverCancel:
		return "HandoverCancel"
	case ProcedureCodeHandoverNotification:
		return "HandoverNotification"
	case ProcedureCodeHandoverPreparation:
		return "HandoverPreparation"
	case ProcedureCodeHandoverResourceAllocation:
		return "HandoverResourceAllocation"
	case ProcedureCodeInitialContextSetup:
		return "InitialContextSetup"
	case ProcedureCodeInitialUEMessage:
		return "InitialUEMessage"
	case ProcedureCodeLocationReportingControl:
		return "LocationReportingControl"
	case ProcedureCodeLocationReportingFailureIndication:
		return "LocationReportingFailureIndication"
	case ProcedureCodeLocationReport:
		return "LocationReport"
	case ProcedureCodeNASNonDeliveryIndication:
		return "NASNonDeliveryIndication"
	case ProcedureCodeNGReset:
		return "NGReset"
	case ProcedureCodeNGSetup:
		return "NGSetup"
	case ProcedureCodeOverloadStart:
		return "OverloadStart"
	case ProcedureCodeOverloadStop:
		return "OverloadStop"
	case ProcedureCodePaging:
		return "Paging"
	case ProcedureCodePathSwitchRequest:
		return "PathSwitchRequest"
	case ProcedureCodePDUSessionResourceModify:
		return "PDUSessionResourceModify"
	case ProcedureCodePDUSessionResourceModifyIndication:
		return "PDUSessionResourceModifyIndication"
	case ProcedureCodePDUSessionResourceRelease:
		return "PDUSessionResourceRelease"
	case ProcedureCodePDUSessionResourceSetup:
		return "PDUSessionResourceSetup"
	case ProcedureCodePDUSessionResourceNotify:
		return "PDUSessionResourceNotify"
	case ProcedureCodePrivateMessage:
		return "PrivateMessage"
	case ProcedureCodePWSCancel:
		return "PWSCancel"
	case ProcedureCodePWSFailureIndication:
		return "PWSFailureIndication"
	case ProcedureCodePWSRestartIndication:
		return "PWSRestartIndication"
	case ProcedureCodeRANConfigurationUpdate:
		return "RANConfigurationUpdate"
	case ProcedureCodeRerouteNASRequest:
		return "RerouteNASRequest"
	case ProcedureCodeRRCInactiveTransitionReport:
		return "RRCInactiveTransitionReport"
	case ProcedureCodeTraceFailureIndication:
		return "TraceFailureIndication"
	case ProcedureCodeTraceStart:
		return "TraceStart"
	case ProcedureCodeUEContextModification:
		return "UEContextModification"
	case ProcedureCodeUEContextRelease:
		return "UEContextRelease"
	case ProcedureCodeUEContextReleaseRequest:
		return "UEContextReleaseRequest"
	case ProcedureCodeUERadioCapabilityCheck:
		return "UERadioCapabilityCheck"
	case ProcedureCodeUERadioCapabilityInfoIndication:
		return "UERadioCapabilityInfoIndication"
	case ProcedureCodeUETNLABindingRelease:
		return "UETNLABindingRelease"
	case ProcedureCodeUplinkNASTransport:
		return "UplinkNASTransport"
	case ProcedureCodeUplinkNonUEAssociatedNRPPaTransport:
		return "UplinkNonUEAssociatedNRPPaTransport"
	case ProcedureCodeUplinkRANConfigurationTransfer:
		return "UplinkRANConfigurationTransfer"
	case ProcedureCodeUplinkRANStatusTransfer:
		return "UplinkRANStatusTransfer"
	case ProcedureCodeUplinkUEAssociatedNRPPaTransport:
		return "UplinkUEAssociatedNRPPaTransport"
	case ProcedureCodeWriteReplaceWarning:
		return "WriteReplaceWarning"
	case ProcedureCodeSecondaryRATDataUsageReport:
		return "SecondaryRATDataUsageReport"
	case ProcedureCodeUplinkRIMInformationTransfer:
		return "UplinkRIMInformationTransfer"
	case ProcedureCodeDownlinkRIMInformationTransfer:
		return "DownlinkRIMInformationTransfer"
	case ProcedureCodeRetrieveUEInformation:
		return "RetrieveUEInformation"
	case ProcedureCodeUEInformationTransfer:
		return "UEInformationTransfer"
	case ProcedureCodeRANCPRelocationIndication:
		return "RANCPRelocationIndication"
	case ProcedureCodeUEContextResume:
		return "UEContextResume"
	case ProcedureCodeUEContextSuspend:
		return "UEContextSuspend"
	case ProcedureCodeUERadioCapabilityIDMapping:
		return "UERadioCapabilityIDMapping"
	case ProcedureCodeHandoverSuccess:
		return "HandoverSuccess"
	case ProcedureCodeUplinkRANEarlyStatusTransfer:
		return "UplinkRANEarlyStatusTransfer"
	case ProcedureCodeDownlinkRANEarlyStatusTransfer:
		return "DownlinkRANEarlyStatusTransfer"
	case ProcedureCodeAMFCPRelocationIndication:
		return "AMFCPRelocationIndication"
	case ProcedureCodeConnectionEstablishmentIndication:
		return "ConnectionEstablishmentIndication"
	case ProcedureCodeBroadcastSessionModification:
		return "BroadcastSessionModification"
	case ProcedureCodeBroadcastSessionRelease:
		return "BroadcastSessionRelease"
	case ProcedureCodeBroadcastSessionSetup:
		return "BroadcastSessionSetup"
	case ProcedureCodeDistributionSetup:
		return "DistributionSetup"
	case ProcedureCodeDistributionRelease:
		return "DistributionRelease"
	case ProcedureCodeMulticastSessionActivation:
		return "MulticastSessionActivation"
	case ProcedureCodeMulticastSessionDeactivation:
		return "MulticastSessionDeactivation"
	case ProcedureCodeMulticastSessionUpdate:
		return "MulticastSessionUpdate"
	case ProcedureCodeMulticastGroupPaging:
		return "MulticastGroupPaging"
	case ProcedureCodeBroadcastSessionReleaseRequired:
		return "BroadcastSessionReleaseRequired"
	case ProcedureCodeTimingSynchronisationStatus:
		return "TimingSynchronisationStatus"
	case ProcedureCodeTimingSynchronisationStatusReport:
		return "TimingSynchronisationStatusReport"
	case ProcedureCodeMTCommunicationHandling:
		return "MTCommunicationHandling"
	case ProcedureCodeRANPagingRequest:
		return "RANPagingRequest"
	case ProcedureCodeBroadcastSessionTransport:
		return "BroadcastSessionTransport"
	default:
		return fmt.Sprintf("unknown procedure code %d", code)
	}
}
