// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-Containers" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

type ProtocolIEContainerPDUSessionResourceSetupRequestIEs struct {
	List []PDUSessionResourceSetupRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerPDUSessionResourceSetupResponseIEs struct {
	List []PDUSessionResourceSetupResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerPDUSessionResourceReleaseCommandIEs struct {
	List []PDUSessionResourceReleaseCommandIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerPDUSessionResourceReleaseResponseIEs struct {
	List []PDUSessionResourceReleaseResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerPDUSessionResourceModifyRequestIEs struct {
	List []PDUSessionResourceModifyRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerPDUSessionResourceModifyResponseIEs struct {
	List []PDUSessionResourceModifyResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerPDUSessionResourceNotifyIEs struct {
	List []PDUSessionResourceNotifyIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerPDUSessionResourceModifyIndicationIEs struct {
	List []PDUSessionResourceModifyIndicationIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerPDUSessionResourceModifyConfirmIEs struct {
	List []PDUSessionResourceModifyConfirmIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerInitialContextSetupRequestIEs struct {
	List []InitialContextSetupRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerInitialContextSetupResponseIEs struct {
	List []InitialContextSetupResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerInitialContextSetupFailureIEs struct {
	List []InitialContextSetupFailureIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUEContextReleaseRequestIEs struct {
	List []UEContextReleaseRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUEContextReleaseCommandIEs struct {
	List []UEContextReleaseCommandIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUEContextReleaseCompleteIEs struct {
	List []UEContextReleaseCompleteIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUEContextResumeRequestIEs struct {
	List []UEContextResumeRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUEContextResumeResponseIEs struct {
	List []UEContextResumeResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUEContextResumeFailureIEs struct {
	List []UEContextResumeFailureIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUEContextSuspendRequestIEs struct {
	List []UEContextSuspendRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUEContextSuspendResponseIEs struct {
	List []UEContextSuspendResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUEContextSuspendFailureIEs struct {
	List []UEContextSuspendFailureIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUEContextModificationRequestIEs struct {
	List []UEContextModificationRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUEContextModificationResponseIEs struct {
	List []UEContextModificationResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUEContextModificationFailureIEs struct {
	List []UEContextModificationFailureIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerRRCInactiveTransitionReportIEs struct {
	List []RRCInactiveTransitionReportIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerRetrieveUEInformationIEs struct {
	List []RetrieveUEInformationIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUEInformationTransferIEs struct {
	List []UEInformationTransferIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerRANCPRelocationIndicationIEs struct {
	List []RANCPRelocationIndicationIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerHandoverRequiredIEs struct {
	List []HandoverRequiredIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerHandoverCommandIEs struct {
	List []HandoverCommandIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerHandoverPreparationFailureIEs struct {
	List []HandoverPreparationFailureIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerHandoverRequestIEs struct {
	List []HandoverRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerHandoverRequestAcknowledgeIEs struct {
	List []HandoverRequestAcknowledgeIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerHandoverFailureIEs struct {
	List []HandoverFailureIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerHandoverNotifyIEs struct {
	List []HandoverNotifyIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerPathSwitchRequestIEs struct {
	List []PathSwitchRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerPathSwitchRequestAcknowledgeIEs struct {
	List []PathSwitchRequestAcknowledgeIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerPathSwitchRequestFailureIEs struct {
	List []PathSwitchRequestFailureIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerHandoverCancelIEs struct {
	List []HandoverCancelIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerHandoverCancelAcknowledgeIEs struct {
	List []HandoverCancelAcknowledgeIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerHandoverSuccessIEs struct {
	List []HandoverSuccessIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUplinkRANEarlyStatusTransferIEs struct {
	List []UplinkRANEarlyStatusTransferIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerDownlinkRANEarlyStatusTransferIEs struct {
	List []DownlinkRANEarlyStatusTransferIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUplinkRANStatusTransferIEs struct {
	List []UplinkRANStatusTransferIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerDownlinkRANStatusTransferIEs struct {
	List []DownlinkRANStatusTransferIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerPagingIEs struct {
	List []PagingIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerInitialUEMessageIEs struct {
	List []InitialUEMessageIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerDownlinkNASTransportIEs struct {
	List []DownlinkNASTransportIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUplinkNASTransportIEs struct {
	List []UplinkNASTransportIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerNASNonDeliveryIndicationIEs struct {
	List []NASNonDeliveryIndicationIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerRerouteNASRequestIEs struct {
	List []RerouteNASRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerNGSetupRequestIEs struct {
	List []NGSetupRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerNGSetupResponseIEs struct {
	List []NGSetupResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerNGSetupFailureIEs struct {
	List []NGSetupFailureIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerRANConfigurationUpdateIEs struct {
	List []RANConfigurationUpdateIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerRANConfigurationUpdateAcknowledgeIEs struct {
	List []RANConfigurationUpdateAcknowledgeIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerRANConfigurationUpdateFailureIEs struct {
	List []RANConfigurationUpdateFailureIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerAMFConfigurationUpdateIEs struct {
	List []AMFConfigurationUpdateIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerAMFConfigurationUpdateAcknowledgeIEs struct {
	List []AMFConfigurationUpdateAcknowledgeIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerAMFConfigurationUpdateFailureIEs struct {
	List []AMFConfigurationUpdateFailureIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerAMFStatusIndicationIEs struct {
	List []AMFStatusIndicationIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerNGResetIEs struct {
	List []NGResetIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerNGResetAcknowledgeIEs struct {
	List []NGResetAcknowledgeIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerErrorIndicationIEs struct {
	List []ErrorIndicationIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerOverloadStartIEs struct {
	List []OverloadStartIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerOverloadStopIEs struct {
	List []OverloadStopIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUplinkRANConfigurationTransferIEs struct {
	List []UplinkRANConfigurationTransferIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerDownlinkRANConfigurationTransferIEs struct {
	List []DownlinkRANConfigurationTransferIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerWriteReplaceWarningRequestIEs struct {
	List []WriteReplaceWarningRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerWriteReplaceWarningResponseIEs struct {
	List []WriteReplaceWarningResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerPWSCancelRequestIEs struct {
	List []PWSCancelRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerPWSCancelResponseIEs struct {
	List []PWSCancelResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerPWSRestartIndicationIEs struct {
	List []PWSRestartIndicationIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerPWSFailureIndicationIEs struct {
	List []PWSFailureIndicationIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerDownlinkUEAssociatedNRPPaTransportIEs struct {
	List []DownlinkUEAssociatedNRPPaTransportIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUplinkUEAssociatedNRPPaTransportIEs struct {
	List []UplinkUEAssociatedNRPPaTransportIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerDownlinkNonUEAssociatedNRPPaTransportIEs struct {
	List []DownlinkNonUEAssociatedNRPPaTransportIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUplinkNonUEAssociatedNRPPaTransportIEs struct {
	List []UplinkNonUEAssociatedNRPPaTransportIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerTraceStartIEs struct {
	List []TraceStartIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerTraceFailureIndicationIEs struct {
	List []TraceFailureIndicationIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerDeactivateTraceIEs struct {
	List []DeactivateTraceIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerCellTrafficTraceIEs struct {
	List []CellTrafficTraceIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerLocationReportingControlIEs struct {
	List []LocationReportingControlIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerLocationReportingFailureIndicationIEs struct {
	List []LocationReportingFailureIndicationIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerLocationReportIEs struct {
	List []LocationReportIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUETNLABindingReleaseRequestIEs struct {
	List []UETNLABindingReleaseRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUERadioCapabilityInfoIndicationIEs struct {
	List []UERadioCapabilityInfoIndicationIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUERadioCapabilityCheckRequestIEs struct {
	List []UERadioCapabilityCheckRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUERadioCapabilityCheckResponseIEs struct {
	List []UERadioCapabilityCheckResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerSecondaryRATDataUsageReportIEs struct {
	List []SecondaryRATDataUsageReportIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUplinkRIMInformationTransferIEs struct {
	List []UplinkRIMInformationTransferIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerDownlinkRIMInformationTransferIEs struct {
	List []DownlinkRIMInformationTransferIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerConnectionEstablishmentIndicationIEs struct {
	List []ConnectionEstablishmentIndicationIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUERadioCapabilityIDMappingRequestIEs struct {
	List []UERadioCapabilityIDMappingRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerUERadioCapabilityIDMappingResponseIEs struct {
	List []UERadioCapabilityIDMappingResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerAMFCPRelocationIndicationIEs struct {
	List []AMFCPRelocationIndicationIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerBroadcastSessionSetupRequestIEs struct {
	List []BroadcastSessionSetupRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerBroadcastSessionSetupResponseIEs struct {
	List []BroadcastSessionSetupResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerBroadcastSessionSetupFailureIEs struct {
	List []BroadcastSessionSetupFailureIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerBroadcastSessionModificationRequestIEs struct {
	List []BroadcastSessionModificationRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerBroadcastSessionModificationResponseIEs struct {
	List []BroadcastSessionModificationResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerBroadcastSessionModificationFailureIEs struct {
	List []BroadcastSessionModificationFailureIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerBroadcastSessionReleaseRequestIEs struct {
	List []BroadcastSessionReleaseRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerBroadcastSessionReleaseRequiredIEs struct {
	List []BroadcastSessionReleaseRequiredIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerBroadcastSessionReleaseResponseIEs struct {
	List []BroadcastSessionReleaseResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerBroadcastSessionTransportRequestIEs struct {
	List []BroadcastSessionTransportRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerBroadcastSessionTransportResponseIEs struct {
	List []BroadcastSessionTransportResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerBroadcastSessionTransportFailureIEs struct {
	List []BroadcastSessionTransportFailureIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerDistributionSetupRequestIEs struct {
	List []DistributionSetupRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerDistributionSetupResponseIEs struct {
	List []DistributionSetupResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerDistributionSetupFailureIEs struct {
	List []DistributionSetupFailureIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerDistributionReleaseRequestIEs struct {
	List []DistributionReleaseRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerDistributionReleaseResponseIEs struct {
	List []DistributionReleaseResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerMulticastSessionActivationRequestIEs struct {
	List []MulticastSessionActivationRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerMulticastSessionActivationResponseIEs struct {
	List []MulticastSessionActivationResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerMulticastSessionActivationFailureIEs struct {
	List []MulticastSessionActivationFailureIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerMulticastSessionDeactivationRequestIEs struct {
	List []MulticastSessionDeactivationRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerMulticastSessionDeactivationResponseIEs struct {
	List []MulticastSessionDeactivationResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerMulticastSessionUpdateRequestIEs struct {
	List []MulticastSessionUpdateRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerMulticastSessionUpdateResponseIEs struct {
	List []MulticastSessionUpdateResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerMulticastSessionUpdateFailureIEs struct {
	List []MulticastSessionUpdateFailureIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerMulticastGroupPagingIEs struct {
	List []MulticastGroupPagingIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerTimingSynchronisationStatusRequestIEs struct {
	List []TimingSynchronisationStatusRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerTimingSynchronisationStatusResponseIEs struct {
	List []TimingSynchronisationStatusResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerTimingSynchronisationStatusFailureIEs struct {
	List []TimingSynchronisationStatusFailureIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerTimingSynchronisationStatusReportIEs struct {
	List []TimingSynchronisationStatusReportIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerMTCommunicationHandlingRequestIEs struct {
	List []MTCommunicationHandlingRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerMTCommunicationHandlingResponseIEs struct {
	List []MTCommunicationHandlingResponseIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerMTCommunicationHandlingFailureIEs struct {
	List []MTCommunicationHandlingFailureIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerRANPagingRequestIEs struct {
	List []RANPagingRequestIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerMBSSessionSetupOrModRequestTransferIEs struct {
	List []MBSSessionSetupOrModRequestTransferIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerMulticastSessionUpdateRequestTransferIEs struct {
	List []MulticastSessionUpdateRequestTransferIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerPDUSessionResourceModifyRequestTransferIEs struct {
	List []PDUSessionResourceModifyRequestTransferIEs `aper:"sizeLB:0,sizeUB:65535"`
}

type ProtocolIEContainerPDUSessionResourceSetupRequestTransferIEs struct {
	List []PDUSessionResourceSetupRequestTransferIEs `aper:"sizeLB:0,sizeUB:65535"`
}
