// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	ReportIntervalMDTPresentMs120   aper.Enumerated = 0
	ReportIntervalMDTPresentMs240   aper.Enumerated = 1
	ReportIntervalMDTPresentMs480   aper.Enumerated = 2
	ReportIntervalMDTPresentMs640   aper.Enumerated = 3
	ReportIntervalMDTPresentMs1024  aper.Enumerated = 4
	ReportIntervalMDTPresentMs2048  aper.Enumerated = 5
	ReportIntervalMDTPresentMs5120  aper.Enumerated = 6
	ReportIntervalMDTPresentMs10240 aper.Enumerated = 7
	ReportIntervalMDTPresentMin1    aper.Enumerated = 8
	ReportIntervalMDTPresentMin6    aper.Enumerated = 9
	ReportIntervalMDTPresentMin12   aper.Enumerated = 10
	ReportIntervalMDTPresentMin30   aper.Enumerated = 11
	ReportIntervalMDTPresentMin60   aper.Enumerated = 12
)

type ReportIntervalMDT struct {
	Value aper.Enumerated `aper:"valueLB:0,valueUB:12"`
}
