// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	ReportingPeriodicityPresentStop    aper.Enumerated = 0
	ReportingPeriodicityPresentSingle  aper.Enumerated = 1
	ReportingPeriodicityPresentMs1000  aper.Enumerated = 2
	ReportingPeriodicityPresentMs2000  aper.Enumerated = 3
	ReportingPeriodicityPresentMs5000  aper.Enumerated = 4
	ReportingPeriodicityPresentMs10000 aper.Enumerated = 5
)

type ReportingPeriodicity struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:5"`
}
