// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	ReportAmountMDTPresentR1        aper.Enumerated = 0
	ReportAmountMDTPresentR2        aper.Enumerated = 1
	ReportAmountMDTPresentR4        aper.Enumerated = 2
	ReportAmountMDTPresentR8        aper.Enumerated = 3
	ReportAmountMDTPresentR16       aper.Enumerated = 4
	ReportAmountMDTPresentR32       aper.Enumerated = 5
	ReportAmountMDTPresentR64       aper.Enumerated = 6
	ReportAmountMDTPresentRinfinity aper.Enumerated = 7
)

type ReportAmountMDT struct {
	Value aper.Enumerated `aper:"valueLB:0,valueUB:7"`
}
