// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	RRCEstablishmentCausePresentEmergency          aper.Enumerated = 0
	RRCEstablishmentCausePresentHighPriorityAccess aper.Enumerated = 1
	RRCEstablishmentCausePresentMtAccess           aper.Enumerated = 2
	RRCEstablishmentCausePresentMoSignalling       aper.Enumerated = 3
	RRCEstablishmentCausePresentMoData             aper.Enumerated = 4
	RRCEstablishmentCausePresentMoVoiceCall        aper.Enumerated = 5
	RRCEstablishmentCausePresentMoVideoCall        aper.Enumerated = 6
	RRCEstablishmentCausePresentMoSMS              aper.Enumerated = 7
	RRCEstablishmentCausePresentMpsPriorityAccess  aper.Enumerated = 8
	RRCEstablishmentCausePresentMcsPriorityAccess  aper.Enumerated = 9
	RRCEstablishmentCausePresentNotAvailable       aper.Enumerated = 10
	RRCEstablishmentCausePresentMoExceptionData    aper.Enumerated = 11
)

type RRCEstablishmentCause struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:9"`
}
