// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

type ScheduledCommunicationTime struct {
	DayofWeek      *aper.BitString                                             `aper:"optional,sizeLB:7,sizeUB:7"`
	TimeofDayStart *int64                                                      `aper:"optional,valueExt,valueLB:0,valueUB:86399"`
	TimeofDayEnd   *int64                                                      `aper:"optional,valueExt,valueLB:0,valueUB:86399"`
	IEExtensions   *ProtocolExtensionContainerScheduledCommunicationTimeExtIEs `aper:"optional"`
}
