// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	SensorNameConfigPresentNothing int = iota /* No components present */
	SensorNameConfigPresentUncompensatedBarometricConfig
	SensorNameConfigPresentUeSpeedConfig
	SensorNameConfigPresentUeOrientationConfig
	SensorNameConfigPresentChoiceExtensions
)

type SensorNameConfig struct {
	Present                       int
	UncompensatedBarometricConfig *aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:0"`
	UeSpeedConfig                 *aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:0"`
	UeOrientationConfig           *aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:0"`
	ChoiceExtensions              *SensorNameConfigExtIEs
}
