// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-PDU-Descriptions" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

const (
	SuccessfulOutcomePresentNothing int = iota /* No components present */
	SuccessfulOutcomePresentAMFConfigurationUpdate
	SuccessfulOutcomePresentBroadcastSessionModification
	SuccessfulOutcomePresentBroadcastSessionRelease
	SuccessfulOutcomePresentBroadcastSessionSetup
	SuccessfulOutcomePresentBroadcastSessionTransport
	SuccessfulOutcomePresentDistributionSetup
	SuccessfulOutcomePresentDistributionRelease
	SuccessfulOutcomePresentHandoverCancel
	SuccessfulOutcomePresentHandoverPreparation
	SuccessfulOutcomePresentHandoverResourceAllocation
	SuccessfulOutcomePresentInitialContextSetup
	SuccessfulOutcomePresentMTCommunicationHandling
	SuccessfulOutcomePresentMulticastSessionActivation
	SuccessfulOutcomePresentMulticastSessionDeactivation
	SuccessfulOutcomePresentMulticastSessionUpdate
	SuccessfulOutcomePresentNGReset
	SuccessfulOutcomePresentNGSetup
	SuccessfulOutcomePresentPathSwitchRequest
	SuccessfulOutcomePresentPDUSessionResourceModify
	SuccessfulOutcomePresentPDUSessionResourceModifyIndication
	SuccessfulOutcomePresentPDUSessionResourceRelease
	SuccessfulOutcomePresentPDUSessionResourceSetup
	SuccessfulOutcomePresentPWSCancel
	SuccessfulOutcomePresentRANConfigurationUpdate
	SuccessfulOutcomePresentTimingSynchronisationStatus
	SuccessfulOutcomePresentUEContextModification
	SuccessfulOutcomePresentUEContextRelease
	SuccessfulOutcomePresentUEContextResume
	SuccessfulOutcomePresentUEContextSuspend
	SuccessfulOutcomePresentUERadioCapabilityCheck
	SuccessfulOutcomePresentUERadioCapabilityIDMapping
	SuccessfulOutcomePresentWriteReplaceWarning
)

type SuccessfulOutcome struct {
	ProcedureCode ProcedureCode
	Criticality   Criticality
	Value         SuccessfulOutcomeValue `aper:"openType,referenceFieldName:ProcedureCode"`
}

type SuccessfulOutcomeValue struct {
	Present                            int
	AMFConfigurationUpdate             *AMFConfigurationUpdateAcknowledge    `aper:"referenceFieldValue:0,valueExt"`
	BroadcastSessionModification       *BroadcastSessionModificationResponse `aper:"referenceFieldValue:66,valueExt"`
	BroadcastSessionRelease            *BroadcastSessionReleaseResponse      `aper:"referenceFieldValue:67,valueExt"`
	BroadcastSessionSetup              *BroadcastSessionSetupResponse        `aper:"referenceFieldValue:68,valueExt"`
	BroadcastSessionTransport          *BroadcastSessionTransportResponse    `aper:"referenceFieldValue:80,valueExt"`
	DistributionSetup                  *DistributionSetupResponse            `aper:"referenceFieldValue:69,valueExt"`
	DistributionRelease                *DistributionReleaseResponse          `aper:"referenceFieldValue:70,valueExt"`
	HandoverCancel                     *HandoverCancelAcknowledge            `aper:"referenceFieldValue:10,valueExt"`
	HandoverPreparation                *HandoverCommand                      `aper:"referenceFieldValue:12,valueExt"`
	HandoverResourceAllocation         *HandoverRequestAcknowledge           `aper:"referenceFieldValue:13,valueExt"`
	InitialContextSetup                *InitialContextSetupResponse          `aper:"referenceFieldValue:14,valueExt"`
	MTCommunicationHandling            *MTCommunicationHandlingResponse      `aper:"referenceFieldValue:78,valueExt"`
	MulticastSessionActivation         *MulticastSessionActivationResponse   `aper:"referenceFieldValue:71,valueExt"`
	MulticastSessionDeactivation       *MulticastSessionDeactivationResponse `aper:"referenceFieldValue:72,valueExt"`
	MulticastSessionUpdate             *MulticastSessionUpdateResponse       `aper:"referenceFieldValue:73,valueExt"`
	NGReset                            *NGResetAcknowledge                   `aper:"referenceFieldValue:20,valueExt"`
	NGSetup                            *NGSetupResponse                      `aper:"referenceFieldValue:21,valueExt"`
	PathSwitchRequest                  *PathSwitchRequestAcknowledge         `aper:"referenceFieldValue:25,valueExt"`
	PDUSessionResourceModify           *PDUSessionResourceModifyResponse     `aper:"referenceFieldValue:26,valueExt"`
	PDUSessionResourceModifyIndication *PDUSessionResourceModifyConfirm      `aper:"referenceFieldValue:27,valueExt"`
	PDUSessionResourceRelease          *PDUSessionResourceReleaseResponse    `aper:"referenceFieldValue:28,valueExt"`
	PDUSessionResourceSetup            *PDUSessionResourceSetupResponse      `aper:"referenceFieldValue:29,valueExt"`
	PWSCancel                          *PWSCancelResponse                    `aper:"referenceFieldValue:32,valueExt"`
	RANConfigurationUpdate             *RANConfigurationUpdateAcknowledge    `aper:"referenceFieldValue:35,valueExt"`
	TimingSynchronisationStatus        *TimingSynchronisationStatusResponse  `aper:"referenceFieldValue:76,valueExt"`
	UEContextModification              *UEContextModificationResponse        `aper:"referenceFieldValue:40,valueExt"`
	UEContextRelease                   *UEContextReleaseComplete             `aper:"referenceFieldValue:41,valueExt"`
	UEContextResume                    *UEContextResumeResponse              `aper:"referenceFieldValue:58,valueExt"`
	UEContextSuspend                   *UEContextSuspendResponse             `aper:"referenceFieldValue:59,valueExt"`
	UERadioCapabilityCheck             *UERadioCapabilityCheckResponse       `aper:"referenceFieldValue:43,valueExt"`
	UERadioCapabilityIDMapping         *UERadioCapabilityIDMappingResponse   `aper:"referenceFieldValue:60,valueExt"`
	WriteReplaceWarning                *WriteReplaceWarningResponse          `aper:"referenceFieldValue:51,valueExt"`
}
