// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	TimeToWaitPresentV1s  aper.Enumerated = 0
	TimeToWaitPresentV2s  aper.Enumerated = 1
	TimeToWaitPresentV5s  aper.Enumerated = 2
	TimeToWaitPresentV10s aper.Enumerated = 3
	TimeToWaitPresentV20s aper.Enumerated = 4
	TimeToWaitPresentV60s aper.Enumerated = 5
)

type TimeToWait struct {
	Value aper.Enumerated `aper:"valueExt,valueLB:0,valueUB:5"`
}
