// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

const (
	TimeToTriggerPresentMs0    aper.Enumerated = 0
	TimeToTriggerPresentMs40   aper.Enumerated = 1
	TimeToTriggerPresentMs64   aper.Enumerated = 2
	TimeToTriggerPresentMs80   aper.Enumerated = 3
	TimeToTriggerPresentMs100  aper.Enumerated = 4
	TimeToTriggerPresentMs128  aper.Enumerated = 5
	TimeToTriggerPresentMs160  aper.Enumerated = 6
	TimeToTriggerPresentMs256  aper.Enumerated = 7
	TimeToTriggerPresentMs320  aper.Enumerated = 8
	TimeToTriggerPresentMs480  aper.Enumerated = 9
	TimeToTriggerPresentMs512  aper.Enumerated = 10
	TimeToTriggerPresentMs640  aper.Enumerated = 11
	TimeToTriggerPresentMs1024 aper.Enumerated = 12
	TimeToTriggerPresentMs1280 aper.Enumerated = 13
	TimeToTriggerPresentMs2560 aper.Enumerated = 14
	TimeToTriggerPresentMs5120 aper.Enumerated = 15
)

type TimeToTrigger struct {
	Value aper.Enumerated `aper:"valueLB:0,valueUB:15"`
}
