// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

type UEAppLayerMeasConfigInfo struct {
	QoEReference                   QoEReference
	ServiceType                    ServiceType
	AreaScopeOfQMC                 *AreaScopeOfQMC `aper:"valueLB:0,valueUB:4"`
	MeasCollEntityIPAddress        TransportLayerAddress
	QoEMeasurementStatus           *aper.Enumerated                                          `aper:"optional,valueExt,valueLB:0,valueUB:0"`
	ContainerForAppLayerMeasConfig aper.OctetString                                          `aper:"optional,sizeLB:1,sizeUB:8000"`
	MeasConfigAppLayerID           *int64                                                    `aper:"optional,valueExt,valueLB:0,valueUB:15"`
	SliceSupportListQMC            *SliceSupportListQMC                                      `aper:"optional"`
	MDTAlignmentInfo               *MDTAlignmentInfo                                         `aper:"valueLB:0,valueUB:1"`
	AvailableRANVisibleQoEMetrics  *AvailableRANVisibleQoEMetrics                            `aper:"valueExt,optional"`
	IEExtensions                   *ProtocolExtensionContainerUEAppLayerMeasConfigInfoExtIEs `aper:"optional"`
}
