// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

type UEDifferentiationInfo struct {
	PeriodicCommunicationIndicator *aper.Enumerated                                       `aper:"optional,valueExt,valueLB:0,valueUB:1"`
	PeriodicTime                   *int64                                                 `aper:"optional,valueExt,valueLB:1,valueUB:3600"`
	ScheduledCommunicationTime     *ScheduledCommunicationTime                            `aper:"valueExt,optional"`
	StationaryIndication           *aper.Enumerated                                       `aper:"optional,valueExt,valueLB:0,valueUB:1"`
	TrafficProfile                 *aper.Enumerated                                       `aper:"optional,valueExt,valueLB:0,valueUB:2"`
	BatteryIndication              *aper.Enumerated                                       `aper:"optional,valueExt,valueLB:0,valueUB:2"`
	IEExtensions                   *ProtocolExtensionContainerUEDifferentiationInfoExtIEs `aper:"optional"`
}
