// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-PDU-Descriptions" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

const (
	UnsuccessfulOutcomePresentNothing int = iota /* No components present */
	UnsuccessfulOutcomePresentAMFConfigurationUpdate
	UnsuccessfulOutcomePresentBroadcastSessionModification
	UnsuccessfulOutcomePresentBroadcastSessionSetup
	UnsuccessfulOutcomePresentBroadcastSessionTransport
	UnsuccessfulOutcomePresentDistributionSetup
	UnsuccessfulOutcomePresentHandoverPreparation
	UnsuccessfulOutcomePresentHandoverResourceAllocation
	UnsuccessfulOutcomePresentInitialContextSetup
	UnsuccessfulOutcomePresentMTCommunicationHandling
	UnsuccessfulOutcomePresentMulticastSessionActivation
	UnsuccessfulOutcomePresentMulticastSessionUpdate
	UnsuccessfulOutcomePresentNGSetup
	UnsuccessfulOutcomePresentPathSwitchRequest
	UnsuccessfulOutcomePresentRANConfigurationUpdate
	UnsuccessfulOutcomePresentTimingSynchronisationStatus
	UnsuccessfulOutcomePresentUEContextModification
	UnsuccessfulOutcomePresentUEContextResume
	UnsuccessfulOutcomePresentUEContextSuspend
)

type UnsuccessfulOutcome struct {
	ProcedureCode ProcedureCode
	Criticality   Criticality
	Value         UnsuccessfulOutcomeValue `aper:"openType,referenceFieldName:ProcedureCode"`
}

type UnsuccessfulOutcomeValue struct {
	Present                      int
	AMFConfigurationUpdate       *AMFConfigurationUpdateFailure       `aper:"referenceFieldValue:0,valueExt"`
	BroadcastSessionModification *BroadcastSessionModificationFailure `aper:"referenceFieldValue:66,valueExt"`
	BroadcastSessionSetup        *BroadcastSessionSetupFailure        `aper:"referenceFieldValue:68,valueExt"`
	BroadcastSessionTransport    *BroadcastSessionTransportFailure    `aper:"referenceFieldValue:80,valueExt"`
	DistributionSetup            *DistributionSetupFailure            `aper:"referenceFieldValue:69,valueExt"`
	HandoverPreparation          *HandoverPreparationFailure          `aper:"referenceFieldValue:12,valueExt"`
	HandoverResourceAllocation   *HandoverFailure                     `aper:"referenceFieldValue:13,valueExt"`
	InitialContextSetup          *InitialContextSetupFailure          `aper:"referenceFieldValue:14,valueExt"`
	MTCommunicationHandling      *MTCommunicationHandlingFailure      `aper:"referenceFieldValue:78,valueExt"`
	MulticastSessionActivation   *MulticastSessionActivationFailure   `aper:"referenceFieldValue:71,valueExt"`
	MulticastSessionUpdate       *MulticastSessionUpdateFailure       `aper:"referenceFieldValue:73,valueExt"`
	NGSetup                      *NGSetupFailure                      `aper:"referenceFieldValue:21,valueExt"`
	PathSwitchRequest            *PathSwitchRequestFailure            `aper:"referenceFieldValue:25,valueExt"`
	RANConfigurationUpdate       *RANConfigurationUpdateFailure       `aper:"referenceFieldValue:35,valueExt"`
	TimingSynchronisationStatus  *TimingSynchronisationStatusFailure  `aper:"referenceFieldValue:76,valueExt"`
	UEContextModification        *UEContextModificationFailure        `aper:"referenceFieldValue:40,valueExt"`
	UEContextResume              *UEContextResumeFailure              `aper:"referenceFieldValue:58,valueExt"`
	UEContextSuspend             *UEContextSuspendFailure             `aper:"referenceFieldValue:59,valueExt"`
}
