// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
From ASN.1 module "NGAP-IEs" found in "38413-i10.asn1"
`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-Go`
*/

package ngapType

import (
	"github.com/omec-project/ngap/v2/aper"
)

type VolumeTimedReportItem struct {
	StartTimeStamp aper.OctetString                                       `aper:"sizeLB:4,sizeUB:4"`
	EndTimeStamp   aper.OctetString                                       `aper:"sizeLB:4,sizeUB:4"`
	UsageCountUL   int64                                                  `aper:"valueLB:0,valueUB:18446744073709551615"`
	UsageCountDL   int64                                                  `aper:"valueLB:0,valueUB:18446744073709551615"`
	IEExtensions   *ProtocolExtensionContainerVolumeTimedReportItemExtIEs `aper:"optional"`
}
